name: famylia_server
description: Backend Famylia — Serverpod
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod: 2.5.1
  serverpod_auth_server: 2.5.1
  crypto: ^3.0.6
  path: ^1.9.1

dev_dependencies:
  serverpod_cli: 2.5.1
  lints: ^4.0.0
